Repository AY2223S2-CS2103T-W15-4/tp, pull requests merged in 2023-03, with the labels that each got.

#101 Update `clear` command for v1.2
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: priority.high

#100 Update `exit` command for v1.2
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: priority.high

#103 Add `add_contact` command for v1.2
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Email.java
  src/main/java/seedu/address/model/contact/Phone.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high

#113 Enhance GUI : add `confirmation dialog`
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/ConfirmationDialog.java
  src/main/resources/images/icon-warning.png
  src/main/resources/view/ConfirmationDialog.css
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: priority.medium

#114 Update test cases for `ClearComand`, `DeleteCommand` and `ExitCommand`
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/ConfirmationDialog.java
  src/main/resources/images/icon-warning.png
  src/main/resources/view/ConfirmationDialog.css
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: priority.medium

#118 Remove duplicate method in InternshipApplication class
  src/main/java/seedu/address/model/person/InternshipApplication.java
Labels: priority.high

#119 Update `clear_by`
  src/main/java/seedu/address/logic/commands/ClearByCommand.java
  src/main/java/seedu/address/logic/parser/ClearByCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Status.java
  src/test/java/seedu/address/logic/commands/ClearByCommandTest.java
Labels: priority.high

#123 Update Find Command to fit InternshipApplication class
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: priority.high

#138 Update Developer Guide for `add_contact` feature
  docs/DeveloperGuide.md
  docs/diagrams/AddContactActivityDiagram.puml
  docs/diagrams/AddContactSequenceDiagram.puml
  docs/images/AddContactActivityDiagram.png
  docs/images/AddContactSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewDateCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/EditStatusCommand.java
  src/main/java/seedu/address/logic/commands/ListArchivedCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewDateCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/InternshipStatus.java
Labels: priority.high

#130 Update GUI for `task` package
  src/main/java/seedu/address/logic/commands/AddInterviewDateCommand.java
  src/main/java/seedu/address/logic/commands/ClearByCommand.java
  src/main/java/seedu/address/logic/commands/task/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearByCommandParser.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.medium

#159 Update GUI layout for `MainWindow`
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/task/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/task/note/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/task/todo/AddTodoCommand.java
  src/main/java/seedu/address/model/task/NoteContent.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MixedPanel.java
  src/main/java/seedu/address/ui/QuickAccessToolbar.java
  src/main/java/seedu/address/ui/ResultDialog.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/SummaryPanel.java
  src/main/java/seedu/address/ui/ViewContentPanel.java
  src/main/java/seedu/address/ui/task/note/NoteListPanel.java
  src/main/java/seedu/address/ui/task/todo/TodoListPanel.java
  src/main/resources/images/help.png
  src/main/resources/images/home.png
  src/main/resources/images/notification.png
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/QuickAccessToolbar.css
  src/main/resources/view/QuickAccessToolbar.fxml
  src/main/resources/view/SummaryPanel.css
  src/main/resources/view/SummaryPanel.fxml
  src/main/resources/view/ViewContentPanel.css
  src/main/resources/view/ViewContentPanel.fxml
  src/main/resources/view/task/ListPanel.css
  src/main/resources/view/task/MixedPanel.fxml
  src/main/resources/view/task/NoteListCard.css
  src/main/resources/view/task/NoteListPanel.fxml
  src/main/resources/view/task/TodoListCard.css
  src/main/resources/view/task/TodoListPanel.fxml
Labels: priority.high

#160 Update User Guide for newly added features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/task/todo/EditDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/task/todo/EditNoteContentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.high

#157 Update user guide for newly added commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListArchivedCommand.java
Labels: documentation, priority.high

#154 Implement all the attributes in InternshipApplication
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewDateCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/EditStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/CompanyName.java
  src/main/java/seedu/address/model/person/InternshipApplication.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/ProgrammingLanguage.java
  src/main/java/seedu/address/model/person/Qualification.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/person/Reflection.java
  src/main/java/seedu/address/model/person/Review.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/storage/JsonAdaptedInternshipApplication.java
  src/main/java/seedu/address/storage/task/todo/JsonAdaptedTodo.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
Labels: priority.medium

#149 Enhance contact management functionality
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/contact/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/ContactParser.java
  src/main/java/seedu/address/logic/parser/contact/DeleteContactCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/EditContactCommandParser.java
  src/main/java/seedu/address/model/person/InternshipApplication.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/contact/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/contact/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/ContactParserTest.java
  src/test/java/seedu/address/logic/parser/contact/DeleteContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/EditContactCommandParserTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/EmailTest.java
  src/test/java/seedu/address/model/contact/PhoneTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/ContactUtil.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/SerializableTestClass.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.high

#145 Add feature to manage resumes and cover letters
  src/main/java/seedu/address/logic/commands/AddInterviewDateCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/EditStatusCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/documents/AddDocumentsCommand.java
  src/main/java/seedu/address/logic/commands/documents/DeleteDocumentsCommand.java
  src/main/java/seedu/address/logic/commands/documents/EditDocumentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/documents/AddDocumentsCommandParser.java
  src/main/java/seedu/address/logic/parser/documents/DeleteDocumentsCommandParser.java
  src/main/java/seedu/address/logic/parser/documents/DocumentsParser.java
  src/main/java/seedu/address/logic/parser/documents/EditDocumentsCommandParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/documents/CoverLetterLink.java
  src/main/java/seedu/address/model/documents/Documents.java
  src/main/java/seedu/address/model/documents/ResumeLink.java
  src/main/java/seedu/address/model/person/InternshipApplication.java
  src/main/java/seedu/address/storage/JsonAdaptedInternshipApplication.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/documents/AddDocumentsCommandTest.java
  src/test/java/seedu/address/logic/commands/documents/DeleteDocumentsCommandTest.java
  src/test/java/seedu/address/logic/commands/documents/EditDocumentsCommandTest.java
  src/test/java/seedu/address/logic/commands/documents/EditDocumentsDescriptorTest.java
  src/test/java/seedu/address/logic/parser/documents/AddDocumentsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/documents/DeleteDocumentsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/documents/DocumentsParserTest.java
  src/test/java/seedu/address/logic/parser/documents/EditDocumentsCommandParserTest.java
  src/test/java/seedu/address/model/documents/CoverLetterLinkTest.java
  src/test/java/seedu/address/model/documents/DocumentsTest.java
  src/test/java/seedu/address/model/documents/ResumeLinkTest.java
  src/test/java/seedu/address/testutil/DocumentsBuilder.java
  src/test/java/seedu/address/testutil/DocumentsUtil.java
  src/test/java/seedu/address/testutil/EditDocumentsDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalDocuments.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.high

#173 Implement Add Internship Via Form
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/control/ControlBox.java
  src/main/java/seedu/address/ui/control/PopupAddInternship.java
  src/main/resources/images/add_button.png
  src/main/resources/images/add_internship.png
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/ControlBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PopupAddInternship.css
  src/main/resources/view/PopupAddInternship.fxml
  src/main/resources/view/ReminderWindow.fxml
Labels: priority.high

#174 Add command box css and more test cases
  src/main/java/seedu/address/logic/parser/ClearByCommandParser.java
  src/main/resources/view/CommandBox.css
  src/test/java/seedu/address/logic/commands/ClearByCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/RevertAllCommandTest.java
  src/test/java/seedu/address/logic/commands/RevertCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearByCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TaskParserTest.java
  src/test/java/seedu/address/testutil/InternshipTodoBuilder.java
Labels: priority.high

#176 Fix bugs in DG.
  docs/DeveloperGuide.md
Labels: documentation

#188 Fix bugs in user guide
  docs/UserGuide.md
Labels: documentation

#189 Fix minor bug in ug
  docs/UserGuide.md
Labels: documentation
